import type { OrganizationProfile, Prospect } from "@/types/prospect";

const evidence = (id: string, title: string, summary: string, sourceLabel: string, date?: string) => ({
  id,
  type: "grant_history" as const,
  title,
  summary,
  sourceLabel,
  date,
});

const factors = [
  { label: "Mission alignment", score: 94, confidence: "high" as const },
  { label: "Geographic alignment", score: 88, confidence: "high" as const },
  { label: "Giving pattern", score: 91, confidence: "medium" as const },
  { label: "Typical grant size", value: "Strong fit", confidence: "medium" as const },
  { label: "Recency", value: "Moderate confidence", confidence: "medium" as const },
];

export const prospects: Prospect[] = [
  {
    id: "horizon-impact",
    name: "Horizon Impact Foundation",
    matchScore: 91,
    typicalGrantMin: 25000,
    typicalGrantMax: 85000,
    focusAreas: ["Youth development", "Food access", "Community health"],
    geography: ["Arizona", "Southwest"],
    recentSignal: "Regional youth initiative noted",
    status: "shortlist",
    summary: "Strong alignment across youth development, food access, and Arizona-based community programming. Historic giving suggests continued interest in scalable regional programs.",
    evidence: [
      evidence("horizon-filing", "Foundation filing", "Historic grantmaking indicates recurring support for community-led programs in the Southwest.", "Synthetic filing record", "2024"),
      evidence("horizon-grants", "Grant history", "Awards in the modeled dataset cluster around youth opportunity and neighborhood health.", "Synthetic grant history", "2022–2024"),
      evidence("horizon-site", "Program priorities", "A mock program statement emphasizes local partnerships and measurable access outcomes.", "Synthetic website summary", "2025"),
      evidence("horizon-update", "Regional initiative", "A fictional public update signals continued interest in Arizona community programs.", "Synthetic announcement", "Mar 2025"),
    ],
    factors,
  },
  {
    id: "northstar-community",
    name: "Northstar Community Trust",
    matchScore: 87,
    typicalGrantMin: 15000,
    typicalGrantMax: 60000,
    focusAreas: ["Education access", "Youth development"],
    geography: ["Arizona", "New Mexico"],
    recentSignal: "New multi-year awards modeled",
    status: "research",
    summary: "A strong programmatic fit with a giving pattern that favors sustained education and youth initiatives.",
    evidence: [evidence("northstar-grants", "Grant history", "Modeled awards show a preference for locally rooted education programs.", "Synthetic grant history", "2021–2024")],
    factors,
  },
  {
    id: "brightbridge-foundation",
    name: "BrightBridge Foundation",
    matchScore: 82,
    typicalGrantMin: 30000,
    typicalGrantMax: 100000,
    focusAreas: ["Food access", "Public health"],
    geography: ["Southwest", "National"],
    recentSignal: "Food systems focus in modeled update",
    status: "outreach",
    summary: "Giving themes overlap with food access and community health, with a grant range that could support a focused pilot.",
    evidence: [evidence("brightbridge-filing", "Foundation filing", "Mock filing data points to mid-sized grants across food access and health.", "Synthetic filing record", "2024")],
    factors,
  },
  {
    id: "civic-growth-fund",
    name: "Civic Growth Fund",
    matchScore: 78,
    typicalGrantMin: 10000,
    typicalGrantMax: 45000,
    focusAreas: ["Community health", "Economic mobility"],
    geography: ["Arizona"],
    status: "research",
    summary: "A promising local prospect with adjacent focus areas; further research is needed to confirm current priorities.",
    evidence: [evidence("civic-update", "Public program update", "A fictional update references neighborhood-level health and access work.", "Synthetic public update", "Jan 2025")],
    factors,
  },
  {
    id: "meridian-social-ventures",
    name: "Meridian Social Ventures",
    matchScore: 74,
    typicalGrantMin: 40000,
    typicalGrantMax: 120000,
    focusAreas: ["Economic mobility", "Education access"],
    geography: ["National"],
    recentSignal: "Leadership transition needs review",
    status: "not_pursued",
    summary: "Grant size and education themes are relevant, though geographic reach and a modeled leadership change lower confidence.",
    evidence: [evidence("meridian-update", "Leadership update", "This synthetic update is included to demonstrate a source requiring human verification.", "Synthetic public update", "Feb 2025")],
    factors,
  },
  {
    id: "evergreen-opportunity",
    name: "Evergreen Opportunity Foundation",
    matchScore: 69,
    typicalGrantMin: 5000,
    typicalGrantMax: 25000,
    focusAreas: ["Youth development", "Arts education"],
    geography: ["Southwest"],
    status: "applied",
    summary: "Some mission overlap and regional fit, with a lower historical award range than the modeled funding need.",
    evidence: [evidence("evergreen-grants", "Grant history", "A fictional award set shows smaller grants to youth and arts programs.", "Synthetic grant history", "2023–2024")],
    factors,
  },
];

export const organizationProfile: OrganizationProfile = {
  name: "Desert Pathways Initiative",
  mission: "Expand opportunity for young people and families through locally led education, food access, and community health programs.",
  geography: ["Phoenix, Arizona", "Southwest"],
  focusAreas: ["Youth development", "Food access", "Community health"],
  fundingNeed: "$250,000 for a two-year neighborhood programs initiative",
};

export const dashboardMetrics = {
  prospectsAnalyzed: 248,
  highFit: 37,
  potentialFunding: "$4.8M",
  activePursuits: 12,
};