services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: gpi
      POSTGRES_PASSWORD: gpi
      POSTGRES_DB: gpi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
